name: iOS

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-11.0

    env:
      DEVELOPER_DIR: /Applications/Xcode_12.3.app

    steps:
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: stable
          docker_version: 19.03
      - name: Checkout backend repo
        uses: actions/checkout@v2
        with:
          repository: Shchepotin/nestjs-boilerplate
          path: backend
      - run: docker-compose --version
      - run: cd backend && cp env-example .env && cd ..
      - run: cd backend && docker-compose up -d && cd ..

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: app

      - name: Install Dependencies
        run: cd app && yarn install

      - name: Update Pods
        run: |
          gem update cocoapods xcodeproj
          cd app/ios && pod install && cd ../..
      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: cd app && yarn start &
      - run: cd app && SIMULATOR_NAME="iPhone 12" yarn test:e2e-build-ios && cd ..
      - run: cd app && SIMULATOR_NAME="iPhone 12" yarn test:e2e-run-ios && cd ..
