name: iOS

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-11.0

    steps:
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: stable
          docker_version: 19.03
      - name: Checkout backend repo
        uses: actions/checkout@v2
        with:
          repository: Shchepotin/nestjs-boilerplate
          path: backend
      - run: docker --version
      - run: ls
      - run: pwd
      - run: docker-compose --version
      - run: cd backend
      - run: ls
      - run: cp env-example .env
      - run: docker-compose up -d
      - run: cd ..

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: app

      - name: Install Dependencies
        run: cd app && yarn install

      - name: Update Pods
        run: |
          gem update cocoapods xcodeproj
          cd ios && pod install && cd ..
      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: SIMULATOR_NAME="iPhone 12" yarn test:e2e-build-ios
      - run: SIMULATOR_NAME="iPhone 12" yarn test:e2e-run-ios
